apiVersion: v1
kind: ConfigMap
metadata:
  # Must match the 'spring.application.name' property of the application
  name: app-config
data:
  application.yml: |-
    info:
      app:
        runtime-config-type: int
